### ISSUE TITLE
Rake tasks with arguments

### ISSUE THREAD

**Issue by thecristen** [lslezak/build-rake#3] opened 2016-01-08 16:26 UTC
This is really cool! Thanks for developing.

For rake tasks that support arguments, is there a way to enter those in? So I can `rake db:reset RAILS_ENV=test` for example?

**Comment by lslezak** [comment] 2016-01-14 17:12
Unfortunately the current architecture of the base `build` package does not allow adding custom parameters to the executed commands easily. The problem is that the tasks (and their respective commands) are collected when an Atom project (directory) in opened. You cannot modify the commands later... :confused: 

Here are some possible workarounds:
- Define a new task (alias) for the needed arguments, e.g. add `db:reset:test` task which will run 
  `db:reset` using the `test` environment.
- Set the Rails environment via the system environment variable, on Linux start Atom using command `RAILS_ENV=test atom /your/project/directory`. This works only for parameters which can be passed also via environment.
- Set up a [custom build command](https://github.com/noseglid/atom-build#specifying-a-custom-build-command).

I'm closing the issue as it cannot be easily implemented in a `build` plugin. Feel free to report an [issue for the base build package](https://github.com/noseglid/atom-build/issues)...

**Closed as completed by lslezak** 2016-01-14 17:12 UTC
